import { ArrowRight, Gem, History, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { templeImages } from "@/lib/temple";
import { useTemple } from "@/components/TempleLayout";

export default function About() {
  const { copy, language } = useTemple();
  const cards = [{ icon: History, title: copy.historyTitle, text: copy.historyText }, { icon: Gem, title: copy.deityTitle, text: copy.deityText }, { icon: ShieldCheck, title: copy.trustTitle, text: copy.trustText }];
  return <div data-testid="about-page"><section className="page-hero" data-testid="about-hero"><div className="container-wide"><p className="eyebrow">{language === "en" ? "The shrine · Est. in faith" : "ಪವಿತ್ರ ಕ್ಷೇತ್ರ · ಭಕ್ತಿಯಲ್ಲಿ ನೆಲೆಸಿದೆ"}</p><h1 className="page-title" data-testid="about-title">{copy.aboutTitle}</h1><p className="page-lede">{copy.aboutText}</p></div></section><section className="section-pad" data-testid="about-story"><div className="container-wide grid gap-12 lg:grid-cols-[0.82fr_1.18fr]"><div className="image-stack tall"><img src={templeImages.courtyard} alt="Temple courtyard" data-testid="about-courtyard-image" /><span className="image-caption">{copy.sacred}</span></div><div><p className="eyebrow">{language === "en" ? "Our story" : "ನಮ್ಮ ಕಥೆ"}</p><h2 className="section-title" data-testid="about-history-title">{copy.historyTitle}</h2><p className="body-copy" data-testid="about-history-copy">{copy.historyText}</p><div className="gold-rule" /><div className="info-grid">{cards.map(({ icon: Icon, title, text }) => <article key={title} className="info-card" data-testid={`about-card-${title.slice(0, 8).toLowerCase().replaceAll(" ", "-")}`}><Icon size={20} className="text-[var(--gold)]" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section><section className="quote-band" data-testid="about-quote"><div className="container-narrow"><span>“</span><p>{language === "en" ? "In every carved stone, a prayer. In every visitor, a blessing." : "ಪ್ರತಿ ಕೆತ್ತಿದ ಕಲ್ಲಿನಲ್ಲಿ ಒಂದು ಪ್ರಾರ್ಥನೆ. ಪ್ರತಿ ಭಕ್ತನಲ್ಲಿ ಒಂದು ಆಶೀರ್ವಾದ."}</p><Link to="/poojas" className="text-link light-link" data-testid="about-pooja-link">{copy.bookPooja}<ArrowRight size={16} /></Link></div></section></div>;
}