import { useState } from "react";
import { ArrowRight, Flower2 } from "lucide-react";
import { poojas, type Pooja } from "@/lib/temple";
import { useTemple } from "@/components/TempleLayout";
import InquiryDialog from "@/components/InquiryDialog";

export default function Poojas() {
  const { copy, language } = useTemple();
  const [selected, setSelected] = useState<Pooja | null>(null);
  return <div data-testid="poojas-page"><section className="page-hero compact" data-testid="poojas-hero"><div className="container-wide"><p className="eyebrow">{copy.sacred}</p><h1 className="page-title" data-testid="poojas-title">{copy.poojaTitle}</h1><p className="page-lede">{copy.poojaIntro}</p></div></section><section className="section-pad bg-[var(--surface)]" data-testid="pooja-list-section"><div className="container-wide"><div className="section-heading-row"><div><p className="eyebrow">{language === "en" ? "Daily seva" : "ದೈನಂದಿನ ಸೇವೆ"}</p><h2 className="section-title">{language === "en" ? "Choose your offering" : "ನಿಮ್ಮ ಅರ್ಪಣೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"}</h2></div><span className="count-pill">04 {language === "en" ? "rituals" : "ಸೇವೆಗಳು"}</span></div><div className="pooja-grid">{poojas.map((pooja, index) => <article className="pooja-card" key={pooja.id} data-testid={`pooja-card-${pooja.id}`}><div className="pooja-card-top"><span className="pooja-number">0{index + 1}</span><span className="pooja-icon"><Flower2 size={20} /></span></div><h3 data-testid={`pooja-name-${pooja.id}`}>{pooja.kn}<small>/ {pooja.en}</small></h3><p>{language === "en" ? pooja.descriptionEn : pooja.descriptionKn}</p><div className="pooja-card-bottom"><button className="small-gold-btn" onClick={() => setSelected(pooja)} data-testid={`pooja-book-btn-${pooja.id}`}>{copy.bookNow}<ArrowRight size={14} /></button></div></article>)}</div></div></section>{selected && <InquiryDialog kind="pooja" itemTitle={`${selected.kn} / ${selected.en}`} itemSubtitle={language === "en" ? selected.descriptionEn : selected.descriptionKn} onClose={() => setSelected(null)} />}</div>;
}