export type Language = "en" | "kn";
export type Theme = "day" | "night";

export const templeImages = {
  hero: "https://customer-assets-39nsmqrw.emergentagent.net/job_ab19e64e-071e-455d-ba2e-4200cd877bf1/artifacts/3b4uf6yk_file_00000000512071f6ac2e0755aa79c566.png",
  gateway: "https://customer-assets-39nsmqrw.emergentagent.net/job_ab19e64e-071e-455d-ba2e-4200cd877bf1/artifacts/j3idh28r_file_00000000d25c71f68fdd9de317329e2e.png",
  courtyard: "https://customer-assets-39nsmqrw.emergentagent.net/job_ab19e64e-071e-455d-ba2e-4200cd877bf1/artifacts/i5mgk5dj_file_00000000c19471f6af963617adbae331.png",
  carving: "https://customer-assets-39nsmqrw.emergentagent.net/job_ab19e64e-071e-455d-ba2e-4200cd877bf1/artifacts/p5k19mp3_file_00000000bd0471f594da865f65f01ce6.png",
  water: "https://customer-assets-39nsmqrw.emergentagent.net/job_ab19e64e-071e-455d-ba2e-4200cd877bf1/artifacts/tps8kpnr_file_00000000ace471f682a90cea51e11274.png",
};

export const navItems = [
  { to: "/", en: "Home", kn: "ಮುಖಪುಟ" },
  { to: "/about", en: "About", kn: "ನಮ್ಮ ಬಗ್ಗೆ" },
  { to: "/timings", en: "Timings", kn: "ಸಮಯ" },
  { to: "/poojas", en: "Poojas", kn: "ಪೂಜೆಗಳು" },
  { to: "/donations", en: "Hundi", kn: "ಹುಂಡಿ" },
  { to: "/rooms", en: "Rooms", kn: "ಕೊಠಡಿಗಳು" },
  { to: "/halls", en: "Halls", kn: "ಮಂಟಪಗಳು" },
  { to: "/contact", en: "Contact", kn: "ಸಂಪರ್ಕ" },
];

export type Pooja = {
  id: string;
  kn: string;
  en: string;
  price: string;
  descriptionEn: string;
  descriptionKn: string;
};

export const poojas: Pooja[] = [
  {
    id: "rudra-abisheka",
    kn: "ರುದ್ರಾಭಿಷೇಕ",
    en: "Rudra Abisheka",
    price: "₹ 501",
    descriptionEn: "A sacred bathing ceremony with holy waters, milk, honey and Sri Rudram chanting.",
    descriptionKn: "ಪವಿತ್ರ ತೀರ್ಥ, ಹಾಲು, ಜೇನುತುಪ್ಪ ಮತ್ತು ಶ್ರೀ ರುದ್ರಂ ಪಠಣದೊಂದಿಗೆ ನೆರವೇರುವ ಅಭಿಷೇಕ.",
  },
  {
    id: "ekadasha-rudrabisheka",
    kn: "ಏಕಾದಶ ರುದ್ರಾಭಿಷೇಕ",
    en: "Ekadasha Rudra Abisheka",
    price: "₹ 2,501",
    descriptionEn: "Eleven recitations of Sri Rudram offered for peace, health and prosperity.",
    descriptionKn: "ಶಾಂತಿ, ಆರೋಗ್ಯ ಮತ್ತು ಸಮೃದ್ಧಿಗಾಗಿ ಹನ್ನೊಂದು ಬಾರಿ ಶ್ರೀ ರುದ್ರಂ ಜಪದೊಂದಿಗೆ ಮಹಾ ಪೂಜೆ.",
  },
  {
    id: "ekavara-abisheka",
    kn: "ಏಕವಾರ ರುದ್ರಾಭಿಷೇಕ",
    en: "Ekavara Abisheka",
    price: "₹ 351",
    descriptionEn: "A focused single-cycle abishekam for personal wellness and spiritual harmony.",
    descriptionKn: "ವೈಯಕ್ತಿಕ ಯೋಗಕ್ಷೇಮ ಹಾಗೂ ಆಧ್ಯಾತ್ಮಿಕ ನೆಮ್ಮದಿಗಾಗಿ ನಡೆಸುವ ಏಕವಾರ ಪವಿತ್ರ ಸೇವೆ.",
  },
  {
    id: "panchamrutha-abisheka",
    kn: "ಪಂಚಾಮೃತ ಅಭಿಷೇಕ",
    en: "Panchamrutha Abisheka",
    price: "₹ 1,001",
    descriptionEn: "A special ritual using five sacred nectars: milk, curd, ghee, honey and sugar.",
    descriptionKn: "ಹಾಲು, ಮೊಸರು, ತುಪ್ಪ, ಜೇನುತುಪ್ಪ ಮತ್ತು ಸಕ್ಕರೆಯ ಪಂಚಾಮೃತಗಳಿಂದ ಸಲ್ಲಿಸುವ ವಿಶೇಷ ಅಭಿಷೇಕ.",
  },
];

export type Donation = { id: string; en: string; kn: string; descriptionEn: string; descriptionKn: string };

export const donations: Donation[] = [
  { id: "temple-dev", en: "Temple Development", kn: "ದೇವಾಲಯ ಅಭಿವೃದ್ಧಿ", descriptionEn: "Help preserve ancient stone carvings and grow a welcoming temple campus.", descriptionKn: "ಪುರಾತನ ಕಲ್ಲಿನ ಕೆತ್ತನೆಗಳ ಸಂರಕ್ಷಣೆ ಮತ್ತು ದೇವಾಲಯದ ಆವರಣದ ಅಭಿವೃದ್ಧಿಗೆ ನೆರವಾಗಿ." },
  { id: "society-welfare", en: "Society Welfare", kn: "ಸಮಾಜ ಕಲ್ಯಾಣ", descriptionEn: "Support healthcare camps, education and social upliftment in the Badami region.", descriptionKn: "ಬಾದಾಮಿ ಪ್ರದೇಶದ ವೈದ್ಯಕೀಯ ಶಿಬಿರ, ಶಿಕ್ಷಣ ಮತ್ತು ಸಮಾಜಮುಖಿ ಸೇವೆಗೆ ಬೆಂಬಲ ನೀಡಿ." },
  { id: "annadhana", en: "Annadhana (Food Seva)", kn: "ಅನ್ನದಾನ ಸೇವೆ", descriptionEn: "Offer nutritious prasadam and a warm meal to visiting devotees every day.", descriptionKn: "ಪ್ರತಿದಿನ ಆಗಮಿಸುವ ಭಕ್ತಾದಿಗಳಿಗೆ ಪ್ರಸಾದ ಮತ್ತು ಉಚಿತ ಮಹಾ ಭೋಜನವನ್ನು ಒದಗಿಸಿ." },
  { id: "trust-donation", en: "Trust Donation", kn: "ಟ್ರಸ್ಟ್ ದೇಣಿಗೆ", descriptionEn: "Make a general contribution to the temple religious and charitable trust.", descriptionKn: "ದೇವಾಲಯದ ಧಾರ್ಮಿಕ ಮತ್ತು ದತ್ತಿ ಟ್ರಸ್ಟ್‌ನ ಸಾಮಾನ್ಯ ಸೇವೆಗಳಿಗೆ ಕಾಣಿಕೆ ನೀಡಿ." },
];

export const halls = [
  { id: "large-hall", en: "Large Kalyan Mantapa", kn: "ಬೃಹತ್ ಕಲ್ಯಾಣ ಮಂಟಪ", capacityEn: "1,000+ guests", capacityKn: "1,000+ ಅತಿಥಿಗಳು", image: templeImages.gateway, featuresEn: "Dining hall · Stage & lighting · Green rooms · Parking", featuresKn: "ಭೋಜನ ಶಾಲೆ · ವೇದಿಕೆ ಮತ್ತು ಬೆಳಕು · ವಿಶ್ರಾಂತಿ ಕೊಠಡಿ · ಪಾರ್ಕಿಂಗ್" },
  { id: "medium-hall", en: "Medium Function Hall", kn: "ಮಧ್ಯಮ ಸಭಾಂಗಣ", capacityEn: "300–500 guests", capacityKn: "300–500 ಅತಿಥಿಗಳು", image: templeImages.courtyard, featuresEn: "Traditional hall · Dining space · Dressing rooms", featuresKn: "ಸಾಂಪ್ರದಾಯಿಕ ಸಭಾಂಗಣ · ಭೋಜನ ಸ್ಥಳ · ಅಲಂಕಾರ ಕೊಠಡಿ" },
];

export const ui = {
  en: {
    temple: "Mahakaleshwar Temple",
    place: "Badami",
    tagline: "Where stone remembers devotion",
    sacred: "॥ Om Namah Shivaya ॥",
    bookPooja: "Book a Pooja",
    donate: "Offer to Hundi",
    explore: "Explore the temple",
    learnMore: "Learn our story",
    timings: "Temple timings",
    morning: "Morning Darshan",
    evening: "Evening Darshan",
    open: "Open daily",
    from: "8:00 AM",
    to: "6:00 PM",
    aboutTitle: "A living shrine in Badami stone",
    aboutText: "Set among the red sandstone landscapes of Badami, Mahakaleshwar Temple welcomes every pilgrim with quiet strength. The shrine is held in trust as a place for prayer, service and the passing on of sacred traditions.",
    deityTitle: "The presence of Mahakaleshwar",
    deityText: "Devotees offer prayers to Lord Shiva, the timeless Mahakala, seeking courage, healing and inner stillness. Every abhisheka is an intimate offering of water, light, sound and faith.",
    historyTitle: "A heritage of prayer",
    historyText: "Our placeholder history will be updated by the temple trust. For generations, families have gathered here for festivals, vows and the simple comfort of darshan.",
    trustTitle: "Temple trust",
    trustText: "Sri Mahakaleshwar Religious & Charitable Trust cares for the shrine, its pilgrims and the surrounding community through worship and seva.",
    poojaTitle: "Seva through sacred rituals",
    poojaIntro: "Offer a personal prayer at Mahakaleshwar. Choose a pooja below and our temple team will contact you shortly.",
    bookNow: "Book now",
    donationTitle: "Let your offering become seva",
    donationIntro: "Every contribution supports worship, heritage care, annadhana and the wellbeing of our community.",
    donateNow: "Donate",
    roomsTitle: "A simple stay for pilgrims",
    roomsIntro: "Rest close to the shrine in clean, humble rooms prepared for families and visiting devotees.",
    enquireRoom: "Enquire / book room",
    hallsTitle: "Gather in a sacred setting",
    hallsIntro: "Make your family occasion meaningful with a traditional hall in the temple campus.",
    enquire: "Enquire",
    contactTitle: "Come sit in the presence of Shiva",
    contactIntro: "We would be glad to help with darshan, pooja, stay and hall enquiries.",
    address: "Temple Road, Badami, Karnataka 587201",
    phone: "+91 00000 00000",
    email: "temple@example.com",
    sendMessage: "Send enquiry",
    footerLine: "A place of prayer, heritage and service.",
    placeholder: "Placeholder audio · replace with temple recording",
    liveDarshan: "Darshan open",
    selectPooja: "Selected seva",
    optional: "optional",
    cancel: "Cancel",
    name: "Your name",
    phoneLabel: "Phone number",
    date: "Preferred date",
    nakshatra: "Nakshatra / Gotra",
    amount: "Offering amount",
    donor: "Donor name",
    message: "Your message",
    submitBooking: "Submit booking",
    submitDonation: "Submit offering",
    successBooking: "Booking submitted, we'll contact you shortly.",
    successDonation: "Thank you. Your offering intention has been received.",
    successEnquiry: "Enquiry submitted, we'll contact you shortly.",
    required: "Please complete the required fields.",
    facilities: ["Bed, bedsheet and pillow provided", "Clean non-AC rooms", "Attached bathroom with hot & cold water", "24/7 purified drinking water", "24/7 pilgrim service available"],
  },
  kn: {
    temple: "ಮಹಾಕಾಳೇಶ್ವರ ದೇವಸ್ಥಾನ",
    place: "ಬಾದಾಮಿ",
    tagline: "ಕಲ್ಲಿನಲ್ಲಿ ಉಳಿದ ಭಕ್ತಿಯ ನೆನಪು",
    sacred: "॥ ಓಂ ನಮಃ ಶಿವಾಯ ॥",
    bookPooja: "ಪೂಜೆ ಬುಕ್ ಮಾಡಿ",
    donate: "ಹುಂಡಿಗೆ ಕಾಣಿಕೆ",
    explore: "ದೇವಾಲಯವನ್ನು ನೋಡಿ",
    learnMore: "ನಮ್ಮ ಕಥೆ ತಿಳಿಯಿರಿ",
    timings: "ದೇವಾಲಯದ ಸಮಯ",
    morning: "ಬೆಳಗಿನ ದರ್ಶನ",
    evening: "ಸಂಜೆಯ ದರ್ಶನ",
    open: "ಪ್ರತಿದಿನ ತೆರೆದಿರುತ್ತದೆ",
    from: "ಬೆಳಿಗ್ಗೆ 8:00",
    to: "ಸಂಜೆ 6:00",
    aboutTitle: "ಬಾದಾಮಿ ಕಲ್ಲಿನಲ್ಲಿ ಜೀವಂತ ದೇವಾಲಯ",
    aboutText: "ಬಾದಾಮಿಯ ಕೆಂಪು ಮರಳುಗಲ್ಲಿನ ಸೌಂದರ್ಯದ ನಡುವೆ ಮಹಾಕಾಳೇಶ್ವರ ದೇವಸ್ಥಾನವು ಪ್ರತಿಯೊಬ್ಬ ಭಕ್ತನನ್ನೂ ಶಾಂತ ಶಕ್ತಿಯಿಂದ ಸ್ವಾಗತಿಸುತ್ತದೆ. ಇದು ಪ್ರಾರ್ಥನೆ, ಸೇವೆ ಮತ್ತು ಪವಿತ್ರ ಸಂಪ್ರದಾಯಗಳ ತಾಣವಾಗಿದೆ.",
    deityTitle: "ಮಹಾಕಾಳೇಶ್ವರನ ಸಾನ್ನಿಧ್ಯ",
    deityText: "ಭಕ್ತರು ಕಾಲಾತೀತ ಮಹಾಕಾಳೇಶ್ವರನಿಗೆ ಧೈರ್ಯ, ಆರೋಗ್ಯ ಮತ್ತು ಮನಶ್ಶಾಂತಿಗಾಗಿ ಪ್ರಾರ್ಥಿಸುತ್ತಾರೆ. ಪ್ರತಿಯೊಂದು ಅಭಿಷೇಕವೂ ನೀರು, ಬೆಳಕು, ನಾದ ಮತ್ತು ಭಕ್ತಿಯ ಅರ್ಪಣೆಯಾಗಿದೆ.",
    historyTitle: "ಪ್ರಾರ್ಥನೆಯ ಪರಂಪರೆ",
    historyText: "ನಮ್ಮ ದೇವಾಲಯದ ಇತಿಹಾಸದ ವಿವರಗಳನ್ನು ಟ್ರಸ್ಟ್ ಶೀಘ್ರದಲ್ಲೇ ಹಂಚಿಕೊಳ್ಳಲಿದೆ. ಪೀಳಿಗೆಗಳಿಂದ ಕುಟುಂಬಗಳು ಇಲ್ಲಿ ಹಬ್ಬ, ಹರಕೆ ಮತ್ತು ದರ್ಶನಕ್ಕಾಗಿ ಸೇರುತ್ತಿವೆ.",
    trustTitle: "ದೇವಾಲಯದ ಟ್ರಸ್ಟ್",
    trustText: "ಶ್ರೀ ಮಹಾಕಾಳೇಶ್ವರ ಧಾರ್ಮಿಕ ಮತ್ತು ದತ್ತಿ ಟ್ರಸ್ಟ್ ದೇವಾಲಯ, ಭಕ್ತರು ಮತ್ತು ಸುತ್ತಮುತ್ತಲಿನ ಸಮುದಾಯದ ಸೇವೆಯನ್ನು ಮಾಡುತ್ತದೆ.",
    poojaTitle: "ಪವಿತ್ರ ಸೇವೆಯ ಮೂಲಕ ಭಕ್ತಿ",
    poojaIntro: "ಮಹಾಕಾಳೇಶ್ವರನಲ್ಲಿ ನಿಮ್ಮ ಪ್ರಾರ್ಥನೆ ಸಲ್ಲಿಸಿ. ಕೆಳಗಿನ ಪೂಜೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ; ನಮ್ಮ ತಂಡ ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
    bookNow: "ಈಗ ಬುಕ್ ಮಾಡಿ",
    donationTitle: "ನಿಮ್ಮ ಕಾಣಿಕೆ ಸೇವೆಯಾಗಲಿ",
    donationIntro: "ಪ್ರತಿ ಕಾಣಿಕೆಯೂ ಪೂಜೆ, ಪರಂಪರೆ ಸಂರಕ್ಷಣೆ, ಅನ್ನದಾನ ಮತ್ತು ಸಮುದಾಯದ ಕಲ್ಯಾಣಕ್ಕೆ ನೆರವಾಗುತ್ತದೆ.",
    donateNow: "ಕಾಣಿಕೆ ನೀಡಿ",
    roomsTitle: "ಭಕ್ತರಿಗಾಗಿ ಸರಳ ವಸತಿ",
    roomsIntro: "ಕುಟುಂಬಗಳು ಮತ್ತು ಭಕ್ತರಿಗಾಗಿ ಸಿದ್ಧಪಡಿಸಿದ ಸ್ವಚ್ಛ ಕೊಠಡಿಗಳಲ್ಲಿ ದೇವಾಲಯದ ಸಮೀಪ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.",
    enquireRoom: "ಕೊಠಡಿ ವಿಚಾರಿಸಿ / ಬುಕ್ ಮಾಡಿ",
    hallsTitle: "ಪವಿತ್ರ ಸ್ಥಳದಲ್ಲಿ ನಿಮ್ಮ ಸಮಾರಂಭ",
    hallsIntro: "ದೇವಾಲಯದ ಆವರಣದಲ್ಲಿರುವ ಸಾಂಪ್ರದಾಯಿಕ ಮಂಟಪದಲ್ಲಿ ಕುಟುಂಬದ ಸಮಾರಂಭವನ್ನು ಅರ್ಥಪೂರ್ಣವಾಗಿಸಿ.",
    enquire: "ವಿಚಾರಿಸಿ",
    contactTitle: "ಶಿವನ ಸಾನ್ನಿಧ್ಯಕ್ಕೆ ಬನ್ನಿ",
    contactIntro: "ದರ್ಶನ, ಪೂಜೆ, ವಸತಿ ಮತ್ತು ಮಂಟಪದ ವಿಚಾರಣೆಗಳಿಗೆ ಸಹಾಯ ಮಾಡಲು ನಾವು ಸಂತೋಷಪಡುತ್ತೇವೆ.",
    address: "ದೇವಸ್ಥಾನ ರಸ್ತೆ, ಬಾದಾಮಿ, ಕರ್ನಾಟಕ 587201",
    phone: "+91 00000 00000",
    email: "temple@example.com",
    sendMessage: "ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
    footerLine: "ಪ್ರಾರ್ಥನೆ, ಪರಂಪರೆ ಮತ್ತು ಸೇವೆಯ ತಾಣ.",
    placeholder: "ಪ್ಲೇಸ್‌ಹೋಲ್ಡರ್ ಆಡಿಯೋ · ದೇವಾಲಯದ ಧ್ವನಿಮುದ್ರಣದಿಂದ ಬದಲಿಸಿ",
    liveDarshan: "ದರ್ಶನ ತೆರೆದಿದೆ",
    selectPooja: "ಆಯ್ಕೆ ಮಾಡಿದ ಸೇವೆ",
    optional: "ಐಚ್ಛಿಕ",
    cancel: "ರದ್ದುಮಾಡಿ",
    name: "ನಿಮ್ಮ ಹೆಸರು",
    phoneLabel: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    date: "ಆದ್ಯತೆಯ ದಿನಾಂಕ",
    nakshatra: "ನಕ್ಷತ್ರ / ಗೋತ್ರ",
    amount: "ಕಾಣಿಕೆ ಮೊತ್ತ",
    donor: "ದಾನಿಗಳ ಹೆಸರು",
    message: "ನಿಮ್ಮ ಸಂದೇಶ",
    submitBooking: "ಬುಕಿಂಗ್ ಸಲ್ಲಿಸಿ",
    submitDonation: "ಕಾಣಿಕೆ ಸಲ್ಲಿಸಿ",
    successBooking: "ಬುಕಿಂಗ್ ಸಲ್ಲಿಸಲಾಗಿದೆ, ನಾವು ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
    successDonation: "ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ಕಾಣಿಕೆಯ ಉದ್ದೇಶವನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ.",
    successEnquiry: "ವಿಚಾರಣೆ ಸಲ್ಲಿಸಲಾಗಿದೆ, ನಾವು ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
    required: "ದಯವಿಟ್ಟು ಅಗತ್ಯವಿರುವ ಮಾಹಿತಿಯನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    facilities: ["ಹಾಸಿಗೆ, ಬೆಡ್‌ಶೀಟ್ ಮತ್ತು ದಿಂಬು ಲಭ್ಯ", "ಸ್ವಚ್ಛ ನಾನ್-ಎಸಿ ಕೊಠಡಿಗಳು", "ಬಿಸಿ ಮತ್ತು ತಣ್ಣೀರು ಇರುವ ಸ್ನಾನಗೃಹ", "24/7 ಶುದ್ಧ ಕುಡಿಯುವ ನೀರು", "24/7 ಭಕ್ತರ ಸೇವೆ ಲಭ್ಯ"],
  },
} as const;

export type Copy = (typeof ui)[Language];